[workspace]
resolver = "2"
members = [
    "ckb-debugger",
    "ckb-mock-tx-types",
    "ckb-vm-debug-utils",
    "ckb-vm-pprof",
    "ckb-vm-pprof-converter",
    "ckb-vm-pprof-protos",
    "ckb-vm-signal-profiler",
]

[patch.crates-io]
ckb-chain-spec = { git = "https://github.com/libraries/ckb", branch = "v0.200.0-rc2" }
ckb-hash = { git = "https://github.com/libraries/ckb", branch = "v0.200.0-rc2" }
ckb-jsonrpc-types = { git = "https://github.com/libraries/ckb", branch = "v0.200.0-rc2" }
ckb-script = { git = "https://github.com/libraries/ckb", branch = "v0.200.0-rc2" }
ckb-traits = { git = "https://github.com/libraries/ckb", branch = "v0.200.0-rc2" }
ckb-types = { git = "https://github.com/libraries/ckb", branch = "v0.200.0-rc2" }
