[package]
name = "ckb-mock-tx-types"
description = "CKB mock transaction types"
version = "0.109.0"
license = "MIT"
edition = "2021"
authors = ["Nervos Core Dev <dev@nervos.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { git = "https://github.com/nervosnetwork/ckb", branch = "ckb2023" }
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", branch = "ckb2023" }
ckb-traits = { git = "https://github.com/nervosnetwork/ckb", branch = "ckb2023" }
serde = { version = "1.0", features=["derive"] }
